### ISSUE TITLE
OC only: center image labels

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#963]
> We would like to have the label images always centered.

> We noticed that the label image also always ends about 2/3 of the way across the page (at least in a non-grid form). Could this be extended to allow the image to span the full form width (perhaps minus 10% or so as a margin)?

* [x] test widgets form in Grid theme (anything with images messed up?)
* [x] test widgets form in regular theme
* [x] test with form that has image labels in Grid theme
* [x] same in regular theme

**Comment by MartijnR** [comment]
We can easily tweak this further. For now I've applied these rules (in `master`):

```css
// centering of image labels
.or .question-label~img {
    margin-left: auto;
    margin-right: auto;
    max-width: 90%;
    max-height: inherit;
}
```

This means that an image won't be stretched, to 90% width but if the image own size width is more than 90% of the form width, it will show in maximum width.

The height restriction was removed which may or may not be desirable. It is normally set to `300px`.
